# Generated by Django 2.0.2 on 2018-02-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('week_name', models.CharField(max_length=200, verbose_name='name')),
                ('week_started', models.DateField(default='2017-01-01')),
                ('week_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rate')),
                ('time_tracked', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='time tracked')),
                ('highlights', models.TextField(blank=True)),
                ('leaks', models.TextField(blank=True)),
                ('bu_hi_time', models.IntegerField(default=0, verbose_name='Hi%')),
                ('bu_mid_time', models.IntegerField(default=0, verbose_name='Mid%')),
                ('bu_lo_time', models.IntegerField(default=0, verbose_name='Lo%')),
                ('bu_math_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Math')),
                ('bu_math_details', models.TextField(blank=True, verbose_name='Math description')),
                ('bu_cs_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Computer Science')),
                ('bu_cs_details', models.TextField(blank=True, verbose_name='CS description')),
                ('bu_lg_de_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Deutsch')),
                ('bu_lg_fr_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='French')),
                ('bu_lg_jap_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Japanese')),
                ('bu_lg_de_details', models.TextField(blank=True, verbose_name='Deutsch details')),
                ('bu_lg_fr_details', models.TextField(blank=True, verbose_name='French details')),
                ('bu_lg_jap_details', models.TextField(blank=True, verbose_name='Japanese details')),
                ('bu_others_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Others')),
                ('bu_others_details', models.TextField(blank=True, verbose_name='Others details')),
                ('opk_tourne_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tourne')),
                ('opk_tourne_details', models.TextField(blank=True, verbose_name='Tourne details')),
                ('opk_gobasquing_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='GoBasquing')),
                ('opk_gobasquing_details', models.TextField(blank=True, verbose_name='GoBasquing details')),
                ('opk_urgoiti_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Urgoiti')),
                ('opk_urgoiti_details', models.TextField(blank=True, verbose_name='Urgoiti details')),
                ('opk_other_tours_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Other tours')),
                ('opk_other_tours_details', models.TextField(blank=True, verbose_name='Other tours details')),
                ('opk_tries_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tries')),
                ('opk_tries_details', models.TextField(blank=True, verbose_name='Tries details')),
                ('kic_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='KiC')),
                ('kic_details', models.TextField(blank=True, verbose_name='KiC details')),
                ('stuff_shared_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Shared Time')),
                ('stuff_shared_details', models.TextField(blank=True, verbose_name='Shared Time details')),
                ('stuff_ortu_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ortu')),
                ('stuff_ortu_details', models.TextField(blank=True, verbose_name='Ortu details')),
                ('stuff_others_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Others')),
                ('stuff_others_details', models.TextField(blank=True, verbose_name='Others details')),
                ('stuff_sleeping_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Sleep')),
                ('junk_stuff_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Junk')),
                ('sport_intensity', models.IntegerField(default=0, verbose_name='Intensity')),
                ('sport_cal', models.IntegerField(default=0, verbose_name='Calories')),
                ('sport_run_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Running time')),
                ('sport_run_dst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Distance')),
                ('sport_run_alt', models.IntegerField(default=0, verbose_name='Altitude')),
                ('sport_run_pace', models.DurationField(null=True, verbose_name='Pace')),
                ('sport_bike_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Bike time')),
                ('sport_bike_dst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Distance')),
                ('sport_bike_alt', models.IntegerField(default=0, verbose_name='Altitude')),
                ('sport_others_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Other Sport')),
                ('sport_others_details', models.TextField(blank=True, verbose_name='Other details')),
            ],
        ),
    ]
