# Generated by Django 2.0.2 on 2018-03-19 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly',
            name='sport_run_pace',
            field=models.DurationField(default=datetime.timedelta(0, 360), verbose_name='Pace'),
        ),
    ]
